aspect_ratio:
  type: string
  default: "3/4.5"
safari_fix:
  type: string
  default: "150%"
  description: "Divide height/width of the aspect ratio and give the value in percentage. E.g.: 4.5/3 = 150%"
image_resize:
  type: string
  default: "contain"
  description: "How topic thumbnails should be resized to fit the cards. Can be one of the following: contain, cover, fill, none, scale-down"
featured_category:
  type: integer
  default: 0
featured_tags:
  type: list
  list_type: tag
  default: "featured"
topic_source:
  type: enum
  default: "latest"
  choices:
    - latest
    - top/all
    - top/yearly
    - top/quarterly
    - top/monthly
    - top/weekly
    - top/daily
randomize_topics: true
display_when_unfiltered: true
display_on_categories: true
display_categories: 
  type: list
  list_type: category
  default: ""
maximum_topic_count: 4
scope_to_category: false
display_mobile: true
